version: 2
jobs:
  build:
    working_directory: ~/zond/android-diplicity
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      KEYSTORE: ${HOME}/${CIRCLE_PROJECT_REPONAME}/signing.keystore
      KEY_ALIAS: release
    docker:
      - image: circleci/android:api-26-alpha
    steps:
    - restore_cache:
        keys:
        # This branch if available
        - v1-dep-{{ .Branch }}-
        # Default branch if not
        - v1-dep-master-
        # Any branch if there are none on the default branch - this should be unnecessary if you have your default branch configured correctly
        - v1-dep-
    - checkout
    - run: ./circle/download_keystore.sh
    - run: ./gradlew dependencies
    # Save dependency cache
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
        # This is a broad list of cache paths to include many possible development environments
        # You can probably delete some of these entries
        - vendor/bundle
        - ~/virtualenvs
        - ~/.m2
        - ~/.ivy2
        - ~/.bundle
        - ~/.go_workspace
        - ~/.gradle
        - ~/.cache/bower
    - run: env KEYSTORE="${HOME}/${CIRCLE_USERNAME}/${CIRCLE_PROJECT_REPONAME}" ./gradlew assembleRelease
    - run: cp -r app/build/outputs $CIRCLE_ARTIFACTS
    - run: ./circle/create_release.sh
    # Save test results
    - store_test_results:
        path: /tmp/circleci-test-results
    # Save artifacts
    - store_artifacts:
        path: /tmp/circleci-artifacts
    - store_artifacts:
        path: /tmp/circleci-test-results
